name: rentpay_app
description: RentPay Rental Billing Application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0

  # Google Sign-In
  google_sign_in: ^6.2.1

  # Image Upload
  image_picker: ^1.0.7
  http: ^1.2.1

  # Blur Detection
  flutter_image_compress: ^2.3.0

  fl_chart: ^0.68.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
