name: rentpay_app
description: RentPay Rental Billing Application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  cloud_firestore: ^6.10.0
  firebase_storage: ^13.6.0
  firebase_messaging: ^16.7.0

  # Local Notifications
  flutter_local_notifications: ^22.3.1

  # Google Sign-In
  google_sign_in: 6.2.2

  # Image Upload
  image_picker: ^1.2.3
  image_cropper: ^12.2.1
  http: ^1.2.1

  # Blur Detection / Image Compression
  flutter_image_compress: ^2.3.0

  # Free On-Device Receipt OCR
  google_mlkit_text_recognition: ^0.13.1

  # Charts
  fl_chart: ^1.2.0
  intl: ^0.20.2

  # PDF / Print
  pdf: ^3.11.3
  printing: ^5.13.1
  cloud_functions: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/rentpay_logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000"
  image: assets/images/rentpay_logo.png
  android_12:
    color: "#000000"
    image: assets/images/rentpay_logo.png
    icon_background_color: "#000000"
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/rentpay_logo.png
    - assets/images/juggernaut_logo.png
    - assets/rentpay_logo.png

  fonts:
    - family: RentpayScript
      fonts:
        - asset: assets/fonts/GrandHotel-Regular.ttf